# Generated by Django 4.1.7 on 2023-03-28 23:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pest', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=200)),
                ('author', models.IntegerField()),
                ('host', models.CharField(max_length=200)),
                ('number', models.IntegerField()),
                ('cum_num', models.IntegerField()),
                ('image', models.ImageField(upload_to='images')),
                ('image_data', models.BinaryField(null=True)),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('time_created', models.TimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='USER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='username')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date_created')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('password1', models.CharField(max_length=128, verbose_name='password1')),
            ],
        ),
    ]
