# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\User\Documents\UM\Year 3\Sem 2\KIX3001\ICMS\gui\src\Logout.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Logout(object):
    def setupUi(self, Logout):
        Logout.setObjectName("Logout")
        Logout.resize(288, 140)
        self.verticalLayout = QtWidgets.QVBoxLayout(Logout)
        self.verticalLayout.setContentsMargins(20, 10, 20, 10)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.confirm_message = QtWidgets.QLabel(Logout)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.confirm_message.setFont(font)
        self.confirm_message.setObjectName("confirm_message")
        self.verticalLayout.addWidget(self.confirm_message)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(20)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.yes_button = QtWidgets.QPushButton(Logout)
        self.yes_button.setObjectName("yes_button")
        self.horizontalLayout.addWidget(self.yes_button)
        self.cancel_button = QtWidgets.QPushButton(Logout)
        self.cancel_button.setObjectName("cancel_button")
        self.horizontalLayout.addWidget(self.cancel_button)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Logout)
        QtCore.QMetaObject.connectSlotsByName(Logout)

    def retranslateUi(self, Logout):
        _translate = QtCore.QCoreApplication.translate
        Logout.setWindowTitle(_translate("Logout", "Dialog"))
        self.confirm_message.setText(_translate("Logout", "Are you sure?"))
        self.yes_button.setText(_translate("Logout", "Yes"))
        self.cancel_button.setText(_translate("Logout", "Cancel"))
