# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\src\Sidebar.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_sidebar(object):
    def setupUi(self, sidebar):
        sidebar.setObjectName("sidebar")
        sidebar.resize(224, 853)
        self.horizontalLayout = QtWidgets.QHBoxLayout(sidebar)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.logo = ClickableLabel(sidebar)
        self.logo.setEnabled(True)
        self.logo.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap(".\\src\\../Image/Register/ICMS.png"))
        self.logo.setScaledContents(False)
        self.logo.setAlignment(QtCore.Qt.AlignCenter)
        self.logo.setObjectName("logo")
        self.verticalLayout_2.addWidget(self.logo)
        self.widget = QtWidgets.QWidget(sidebar)
        self.widget.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.widget.setObjectName("widget")
        self.verticalLayout_2.addWidget(self.widget)
        self.sidebar_home = ClickableLabel(sidebar)
        self.sidebar_home.setMinimumSize(QtCore.QSize(0, 0))
        self.sidebar_home.setMouseTracking(False)
        self.sidebar_home.setAutoFillBackground(False)
        self.sidebar_home.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.sidebar_home.setFrameShadow(QtWidgets.QFrame.Plain)
        self.sidebar_home.setText("")
        self.sidebar_home.setPixmap(QtGui.QPixmap(".\\src\\../Image/Register/home.png"))
        self.sidebar_home.setScaledContents(False)
        self.sidebar_home.setAlignment(QtCore.Qt.AlignCenter)
        self.sidebar_home.setObjectName("sidebar_home")
        self.verticalLayout_2.addWidget(self.sidebar_home)
        self.sidebar_camera = QtWidgets.QLabel(sidebar)
        self.sidebar_camera.setStyleSheet("background-color: rgb(0,0,0)")
        self.sidebar_camera.setText("")
        self.sidebar_camera.setPixmap(QtGui.QPixmap(".\\src\\../Image/Register/camera.png"))
        self.sidebar_camera.setAlignment(QtCore.Qt.AlignCenter)
        self.sidebar_camera.setObjectName("sidebar_camera")
        self.verticalLayout_2.addWidget(self.sidebar_camera)
        self.sidebar_record = ClickableLabel(sidebar)
        self.sidebar_record.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.sidebar_record.setText("")
        self.sidebar_record.setPixmap(QtGui.QPixmap(".\\src\\../Image/Register/search.png"))
        self.sidebar_record.setAlignment(QtCore.Qt.AlignCenter)
        self.sidebar_record.setObjectName("sidebar_record")
        self.verticalLayout_2.addWidget(self.sidebar_record)
        self.sidebar_logout = ClickableLabel(sidebar)
        self.sidebar_logout.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.sidebar_logout.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.sidebar_logout.setText("")
        self.sidebar_logout.setPixmap(QtGui.QPixmap(".\\src\\../Image/Register/exit.png"))
        self.sidebar_logout.setAlignment(QtCore.Qt.AlignCenter)
        self.sidebar_logout.setObjectName("sidebar_logout")
        self.verticalLayout_2.addWidget(self.sidebar_logout)
        self.widget_2 = QtWidgets.QWidget(sidebar)
        self.widget_2.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"")
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_2.addWidget(self.widget_2)
        self.horizontalLayout.addLayout(self.verticalLayout_2)


        self.retranslateUi(sidebar)
        QtCore.QMetaObject.connectSlotsByName(sidebar)

    def retranslateUi(self, sidebar):
        _translate = QtCore.QCoreApplication.translate
        sidebar.setWindowTitle(_translate("sidebar", "widget"))
from clickablelabel import ClickableLabel
