# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\controller.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(50, -1, 50, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.button_left = QtWidgets.QPushButton(self.centralwidget)
        self.button_left.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("left.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_left.setIcon(icon)
        self.button_left.setIconSize(QtCore.QSize(75, 75))
        self.button_left.setObjectName("button_left")
        self.horizontalLayout.addWidget(self.button_left)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.button_up = QtWidgets.QPushButton(self.centralwidget)
        self.button_up.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("up.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_up.setIcon(icon1)
        self.button_up.setIconSize(QtCore.QSize(75, 75))
        self.button_up.setObjectName("button_up")
        self.verticalLayout.addWidget(self.button_up)
        self.button_on_off = QtWidgets.QPushButton(self.centralwidget)
        self.button_on_off.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("stop-button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_on_off.setIcon(icon2)
        self.button_on_off.setIconSize(QtCore.QSize(75, 75))
        self.button_on_off.setObjectName("button_on_off")
        self.verticalLayout.addWidget(self.button_on_off)
        self.button_down = QtWidgets.QPushButton(self.centralwidget)
        self.button_down.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("down.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_down.setIcon(icon3)
        self.button_down.setIconSize(QtCore.QSize(75, 75))
        self.button_down.setObjectName("button_down")
        self.verticalLayout.addWidget(self.button_down)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.button_right = QtWidgets.QPushButton(self.centralwidget)
        self.button_right.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_right.setIcon(icon4)
        self.button_right.setIconSize(QtCore.QSize(75, 75))
        self.button_right.setObjectName("button_right")
        self.horizontalLayout.addWidget(self.button_right)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.setStretch(0, 10)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
